CREATE TABLE patient (
  patientId INTEGER IDENTITY(1000, 1),
  name VARCHAR(255) NOT NULL,
  age INTEGER NOT NULL,
  room VARCHAR(255) NOT NULL,
  doctorName VARCHAR(255) NOT NULL,
  admitDate DATETIME DEFAULT CURRENT_TIMESTAMP ,
  expenses VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  mobile INTEGER,
  email VARCHAR(255)
);