name: cicd dev
on:
  push:
    branches:
      - dev
jobs:
  Deploy:
    Uses: ./.github/workflows/build.yml
    with:
      javaVersion: '17'
      webapp: assignment411
    secrets:
      webapppublishprofile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
