name: Build Gradle project

on:
  workflow_call:
    inputs:
      javaVersion:
        required: true
        type: string
      webapp:
        required: true
        type: string
    secrets:
      webapppublishprofile:
        required: true

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: set up java version
        uses: actions/setup-java@v3
        with:
          java-version: '13'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew build