name: Build Gradle project

on:
  workflow_call:
    inputs:
      javaVersion:
        required: true
        type: string
      webapp:
        required: true
        type: string
    secrets:
      webapppublishprofile:
        required: true

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build